version: '3.0'
services:
  syncthing:
    image: syncthing/syncthing:latest
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    environment:
      - PUID=65534
      - PGID=65534
    volumes:
      - /home/ubuntu/syncthing/config/:/var/syncthing/config
      - /home/ubuntu/syncthing/:/var/syncthing
    restart: always

  websocket-boxing-game:
    image: gcr.io/voidvector/websocket-boxing-game:latest
    ports:
      - 8080:8080
    user: nobody:nobody
    restart: always

  solver-webapp:
    image: gcr.io/voidvector/solver-webapp:latest
    ports:
      - 5000:5000
    user: nobody
    restart: always

  showup-services:
    image: gcr.io/voidvector/img-resizer:latest
    ports:
      - 3000:3000
    volumes:
      - /tmp:/tmp
    user: nobody:nobody
    restart: always

  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - 8888:8388
      - 8888:8388/udp
    environment:
      - METHOD=chacha20-ietf-poly1305
      - PASSWORD=xLN5L4kPucpzGjFnyRotpdB4voFtQb9GwZagBRYtg5XAbjMuW5XqMgdx6BsMs5UP
    user: nobody:nobody
    restart: always
