version: '3.0'
services:
  syncthing:
    image: syncthing/syncthing:latest
    ports:
      - 8384:8384
      - 22000:22000
    environment:
      - PUID=65534
      - PGID=65534
    volumes:
      - ${HOME}/syncthing/:/var/syncthing/
    restart: always

  haproxy:
    image: haproxy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ${PWD}/dhparam:/usr/local/etc/haproxy/dhparam
      - /etc/ssl/certs/:/etc/ssl/certs/
      - /etc/ssl/private/:/etc/ssl/private/
    restart: always

  websocket-boxing-game:
    image: gcr.io/voidvector/websocket-boxing-game:latest
    ports:
      - 8080:8080
    user: nobody:nobody
    restart: always

  solver-webapp:
    image: gcr.io/voidvector/solver-webapp:latest
    ports:
      - 5000:5000
    user: nobody:nobody
    restart: always

  # showup-services:
  #   image: gcr.io/voidvector/img-resizer:latest
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - /tmp:/tmp
  #   user: nobody:nobody
  #   restart: always

  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - 8888:8388
      - 8888:8388/udp
    environment:
      - METHOD=chacha20-ietf-poly1305
      - PASSWORD=xLN5L4kPucpzGjFnyRotpdB4voFtQb9GwZagBRYtg5XAbjMuW5XqMgdx6BsMs5UP
    user: nobody:nobody
    restart: always
